Часть 14: Работа с внешними API
kshnyakin/test-guru pull request #13
Opened 2023-10-13 20:33 UTC by kshnyakin

1. Используйте официальный клиент GitHub Octokit

2. Выводите ссылку на созданный gist во flash сообщении

3. Добавьте интернационализацию в сервис GistQuestionService

4. Добавьте модель Gist. У администратора сделайте вывод таблицы всех созданных gist. 
Таблица должна содержать обязательные колонки:
     - Вопрос. Отображаются первые 25 символов тела вопроса в виде ссылки. По клике на ссылку отображается страница вопроса (действие show)
     - Gist URL. Отображается хэш созданного gist в виде ссылки
     - Пользователь. Отображается email пользователя который создал gist

 5. Поместите токен в .env файл и используйте github.com для его загрузки в окружение приложения

2023-10-21 21:10 UTC, VidgarVii requested changes

2023-10-21 21:10 UTC, VidgarVii commented on Gemfile
> +gem 'faraday'
он ведь больше не используется. Лучше удалить

2023-10-21 21:10 UTC, VidgarVii commented on .gitignore
> +/.env
секреты скрыты, это хорошо. Но другому разработчику надо понять какие ЕНВ нужны для проекта.
По этому надо добавить файл .env.example, который будет содержать пустые ЕНВ

2023-10-21 21:10 UTC, VidgarVii commented on app/controllers/test_passings_controller.rb
> +  before_action :set_test_passing, only: %i[show update result gist]
Повод вспомнить про REST.
Gist это ресурс. Значит согласно rails way и REST для создания ресурса и записи в БД объекта Gist должен быть отдельный контроллер с экшеном create

2023-10-21 21:10 UTC, VidgarVii commented on app/controllers/test_passings_controller.rb
> +    flash_options = if result.nil?
По соглашению результата не может не быть.
Будет лучше, если сервис вернет объект, у которого будет метод для определения вызова (`result.success?`). Тебе важно проверить, что пришел не пустой url, это и есть критерий успешного создания гиста.

2023-10-21 21:10 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
еще можно так:
```ruby
[@question.body, *@question.answers.pluck(:body)].join("\n")
```
уменьшит потребление памяти и выглядит лучше

2023-10-22 09:29 UTC, kshnyakin commented on .gitignore
> +/.env
done!

2023-10-22 09:54 UTC, kshnyakin commented on Gemfile
> +gem 'faraday'
Убрал

2023-10-22 10:13 UTC, kshnyakin commented on app/controllers/test_passings_controller.rb
> +    flash_options = if result.nil?
Вернул OpenStruct.

2023-10-22 11:20 UTC, kshnyakin commented on app/controllers/test_passings_controller.rb
> +  before_action :set_test_passing, only: %i[show update result gist]
Вспомнил, Было больно, но теперь вроде бы все по фен-шуй :-)

2023-10-22 11:33 UTC, kshnyakin commented on app/controllers/test_passings_controller.rb
> +    flash_options = if result.nil?
Добавил проверку на пустоту URL.

2023-10-23 04:54 UTC, VidgarVii requested changes

2023-10-23 04:54 UTC, VidgarVii commented on app/controllers/admin/gists_controller.rb
> +  def create
создание гист это функционал обычного пользователя, а не админа.

2023-10-23 04:54 UTC, VidgarVii commented on app/controllers/admin/gists_controller.rb
> +    Gist.create!({
а если октокит не создал гист в гитхаб, то зачем создавать гист в бд?

2023-10-23 04:54 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +      'success?' => result.html_url.present? ? true : false
предикатные методы и так вернут true/false
Не надо за них это делать

2023-10-23 04:54 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +      'response' => result,
Тут происходит передача объекта октокит в контроллер, что создаёт лишнюю зависимость от гема в контроллере. Когда придётся менять гем или он обновится, надо будет еще править контроллер. Это лишняя усложнение кода
Класс GistQuestionService служит своего рода адаптером над октокит. Его задача не только создавать гист. Это он вообще делегирует гему октокит. А скрыть сложность создания гиста и предоставить общий интерфейс, который не зависит от хттп клиента.

2023-10-23 07:39 UTC, kshnyakin commented on app/controllers/admin/gists_controller.rb
> +  def create
Перенес в общий неймспейс.

2023-10-23 07:42 UTC, kshnyakin commented on app/controllers/admin/gists_controller.rb
> +    Gist.create!({
добавил условие при вызове приватного метода `creating_gist`:

`creating_gist(result.response, current_question) if result.success?`

2023-10-23 07:43 UTC, kshnyakin commented on app/services/gist_question_service.rb
> +      'success?' => result.html_url.present? ? true : false
спасибо, убрал

2023-10-23 07:49 UTC, kshnyakin commented on app/services/gist_question_service.rb
> +      'response' => result,
Добавил обработчик ответа от Октотита:
```
  def handle_response(response)
    {
      html_url: response.html_url,
      gist_id: response.id,
    }
  end
  ```

2023-10-23 14:10 UTC, VidgarVii commented on app/controllers/test_passings_controller.rb
> +    id = params[:id]
бесполезная переменная)

старый код смотрелся лучше

2023-10-23 14:16 UTC, kshnyakin commented on app/controllers/test_passings_controller.rb
> +    id = params[:id]
Убрал, осталось после переноса gists в отдельный контроллер.

2023-10-23 14:37 UTC, merged