Часть 15: JavaScript в Rails-приложении
kshnyakin/test-guru pull request #14
Opened 2023-10-23 14:44 UTC by kshnyakin

1. Добавьте сортировку по заголовку теста для таблицы отображения тестов доступных пользователю для прохождения
2. Используя событие input проверяйте совпадение пароля и его подтверждения на странице регистрации пользователя.
   2.1. Пока значения не совпадают информируйте об этом пользователя (например выводя иконку красного цвета). 
   2.2. Информируйте также пользователя в том случае когда значения совпадают (например выводя иконку зелёного цвета).
   2.2. Не информируйте пользователя если поле подтверждения пароля не содержит значения

2023-11-03 07:26 UTC, VidgarVii requested changes

2023-11-03 07:26 UTC, VidgarVii commented on app/javascript/utilities/password-validation.js
> +  let passwordField = document.querySelector('#user_password')
если значение не переопределяется, то принято использовать константу

2023-11-03 07:26 UTC, VidgarVii commented on app/javascript/utilities/password-validation.js
> +  let passwordField = document.querySelector('#user_password')
для поиска элемента по ИД лучше использовать функцию getElementByID

2023-11-03 07:26 UTC, VidgarVii commented on app/javascript/utilities/password-validation.js
> +  passwordField.addEventListener('input', comparePasswords)
прежде чем что-то делать с элементом, надо проверить его наличие. Сейчас на всех страницах кроме логина сыпятся js ошибки

2023-11-03 07:26 UTC, VidgarVii commented on app/javascript/utilities/password-validation.js
> +  let passwordField = document.querySelector('#user_password')
при каждом изменении поля происходит поиск элементов. Эта операция очень дорогая и долгая. Выноси поиск элементов за пределы события

2023-11-03 07:26 UTC, VidgarVii commented on app/javascript/utilities/password-validation.js
> +  passwordConfirmationField.addEventListener('input', comparePasswords)
достаточно 1 слушателя.
Повесить сразу на форму и проверяй 2 поля.

2023-11-03 07:26 UTC, VidgarVii commented on app/javascript/utilities/password-validation.js
> +    case false:
с такими значениями явно не множественный условный оператор нужен

2023-11-03 07:26 UTC, VidgarVii commented on app/javascript/utilities/password-validation.js
> +}
лучше потренироваться в ООП. JS позволяет создавать классы и браузеры это понимают, пусть пока и без инкапсуляций, но уже хоть что-то.
По пробуй создать такой класс утилиту, который принимает html элемент. И далее пусть эта утилита работает только с этим элементов. Таким образом мы сможем пере использоваться утилиту сколько угодно раз с разными элементами без переписывания кода. И так вся логика функционала будет обёрнута в класс, а не просто болтаться где-то снаружи. 
http://old.code.mu/books/javascript/oop/

2023-11-03 07:26 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +   return 0
вся тоже самое. Надо переделать

2023-11-07 20:22 UTC, kshnyakin commented on app/javascript/utilities/sorting.js
> +   return 0
Единственное что пришло в голову как здесь что-то оптимизировать - так это добавил тернарный оператор

2023-11-07 20:22 UTC, kshnyakin commented on app/javascript/utilities/password-validation.js
> +    case false:
поправил на тернарный оператор

2023-11-07 20:23 UTC, kshnyakin commented on app/javascript/utilities/password-validation.js
> +  passwordConfirmationField.addEventListener('input', comparePasswords)
Повесил, определяю

2023-11-07 20:23 UTC, kshnyakin commented on app/javascript/utilities/password-validation.js
> +  let passwordField = document.querySelector('#user_password')
Вынес за пределы события поиск элементов, потом просто передаю в само событие результаты поиска

2023-11-07 20:24 UTC, kshnyakin commented on app/javascript/utilities/password-validation.js
> +  passwordField.addEventListener('input', comparePasswords)
Добавил проверку наличия формы с полями **password** / **password_confirmation**

2023-11-07 20:24 UTC, kshnyakin commented on app/javascript/utilities/password-validation.js
> +  let passwordField = document.querySelector('#user_password')
скорректировался.

2023-11-07 20:47 UTC, kshnyakin commented on app/javascript/utilities/password-validation.js
> +}
Вынес в отдельный класс и за-require-ил :-)

2023-11-08 06:55 UTC, VidgarVii requested changes

2023-11-08 06:55 UTC, VidgarVii commented on app/javascript/utilities/password-validation.js
> +  }
как-то логика размазана м/у 2мя файлами. Проверку пароля можно было делегировать объекту, А не только смену классов

2023-11-08 06:55 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +  var testTitle2 = row2.querySelector('td').textContent
Время глобальных var-ов прошло. при объявлении переменных используй let/const. Так безопасней и код становиться понятней. Обязательно по гугли отличие!

2023-11-08 06:55 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +}
https://github.com/kshnyakin/test-guru/pull/14/files#r1381230133
я имел ввиду что тоже надо переделать используюя ООП

2023-11-08 21:10 UTC, kshnyakin commented on app/javascript/utilities/password-validation.js
> +  }
Делегировал, отрефакторил

2023-11-08 21:46 UTC, kshnyakin commented on app/javascript/utilities/sorting.js
> +}
переделал, упаковал в класс ООП

2023-11-08 21:46 UTC, kshnyakin commented on app/javascript/utilities/sorting.js
> +  var testTitle2 = row2.querySelector('td').textContent
done!

2023-11-09 19:13 UTC, merged