Задание 18: Бейдж и Таймер
kshnyakin/test-guru pull request #17
Opened 2023-12-11 06:17 UTC by kshnyakin

# Бейдж

Разработайте функционал который позволит пользователям получать бэйджи (награды) за успешное прохождение тестов.
1. Бэйджи представляются моделью Badge
2. Пользователь может получать один и тот же бэйдж более одного раза
3. Бэйдж обязательно содержит атрибуты:
    Название
    Имя файла с изображением (Делать загрузку изображений не нужно. Это может быть статический файл с изображением,
    который вручную добавляется в проект. Либо это может быть любой URL с изображением бэйджа)
4. Выдача бэйджов происходит автоматически после завершения теста
5. Управление бэйджами осуществляется администратором
6. При создании бэйджа администратор также назначает правило которое определяет порядок выдачи бэйджа. Примеры правил:
  Выдать бэйдж после успешного прохождения всех тестов из категории Backend
  Выдать бэйдж после успешного прохождения теста с первой попытки
  Выдать бэйдж после успешного прохождения всех тестов определённого уровня
7. Допускается что критерии правил заданы заранее, например на уровне атрибутов модели
8. Пользователь в любой момент времени может посмотреть список всех существующих и заработанных бэйджей

# Таймер

Разработайте функционал который позволит администраторам создавать тесты с таймером, 
а пользователям - проходить такие тесты за отведённое время. При истечении времени таймера тест считается не пройденным.

1. Администратор должен иметь возможность задавать таймер прохождения теста, например, 15 минут
2. При истечении таймера во время прохождения теста пользователь автоматически перенаправляется на страницу с результатом теста
3. При прохождении теста пользователь должен видеть оставшееся количество времени
4. Пользователь не должен иметь возможность как-либо подделать установленное время прохождения теста

2023-12-19 14:43 UTC, VidgarVii requested changes

2023-12-19 14:43 UTC, VidgarVii commented on app/controllers/badge_templates_controller.rb
> +class BadgeTemplatesController < ApplicationController
все баджи можно показать в BadgesController не нарушая rest

2023-12-19 14:43 UTC, VidgarVii commented on app/controllers/test_passings_controller.rb
> +      handle_successful_passing if @test_passing.successful?
@test_passing.successful? по сути это часть бизнес правила. Которое говорит что бадж можно получить только если тест успешно пройден.
 - не стоит перегружать контроллер бизнес-логикой
 - а мне нравится награда типо БЕЗУМИЕ. И чтобы получить её надо завалить тест 5 раз. А с такой проверкой подобные награды уже не возможны =(((

2023-12-19 14:43 UTC, VidgarVii commented on app/controllers/test_passings_controller.rb
> +    @test_passing.update!(successful: true)
вся обработка уже происходит в моделе test_passing

2023-12-19 14:43 UTC, VidgarVii commented on app/controllers/test_passings_controller.rb
> +      # TestsMailer.completed_test(@test_passing).deliver_now
таким комментариям не место в мастер ветке

2023-12-19 14:43 UTC, VidgarVii commented on app/services/badge_award_processing.rb
> +    category_badge_template = BadgeTemplate.find_by(issuance_type: 'all_tests_by_category')
по ТЗ админ может выбирать конкретную категорию или уровень для баджа.

2023-12-19 14:43 UTC, VidgarVii commented on app/services/badge_award_processing.rb
> +    badge_template.badges.create(user_id: @user.id)
здесь стоит использовать bang! метод чтобы сразу убедиться, что код рабочий

2023-12-19 14:43 UTC, VidgarVii commented on app/services/badge_award_processing.rb
> +  end
надо учесть тот момент что кол-во баджев (правил) будет только увеличиваться. Это приведёт к раздутию данного файла и текущего метода. Вспомни как создавали валидации на 1 блоке. А вот то что кол-во файлов увеличиться это не страшно. По этому лучше всего абстрагировать код для правил отдельно в классы. 
От этого так же получим больше пользы, так как распределим обязанности по классам. Данный сервис будет отвечать за выдачу баджа, а за правила пусть отвечают другие объекты. Т.е. нужен объект у которого можно спросить выдавать бадж или нет .

2023-12-19 18:13 UTC, kshnyakin commented on app/controllers/badge_templates_controller.rb
> +class BadgeTemplatesController < ApplicationController
Не очень понял, что здесь имеется в виду, нужно вот это: показывать все шаблоны **BadgesTemplate** на странице списка бейджей конкретного пользователя?

2023-12-19 18:21 UTC, kshnyakin commented on app/controllers/test_passings_controller.rb
> +      # TestsMailer.completed_test(@test_passing).deliver_now
убрал, закрывал на время разработки возможность отправки писем

2023-12-19 18:28 UTC, kshnyakin commented on app/controllers/test_passings_controller.rb
> +    @test_passing.update!(successful: true)
нет, не происходит, в модели есть метод 

```
def successful?
  percentage >= SUCCESS_RATIO
end
```

Который в моменте может сказать успешен ли TestPassing, далее по этому методe запросов типа:
`@user.test_passings.where(successful: true)` - увы не создашь, тогда чтобы понять какие TestPassing были успешно завершены - нужно через map прогонять массив **user.test_passing**

2023-12-20 09:17 UTC, VidgarVii requested changes

2023-12-20 09:17 UTC, VidgarVii commented on app/controllers/admin/badge_templates_controller.rb
> +    params.require(:badge_template).permit(:title, :issuance_type, :category_id, :level, :attempts_number)
При заполнении таблицы у тебя получится почти пусты колонки :issuance_type, :category_id, :level, :attempts_number
Такой подход считается очень плохим. Если колонка почти всегда пустая, то скорей всего она не нужна

2023-12-20 09:17 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    @badge_templates = BadgeTemplate.all
не стоит тут показывать баджи, когда есть и так 2 страницы для баджей.
Достаточно 1 страницы для баджей где юзер увидет свои баджи и все возможные

2023-12-20 09:17 UTC, VidgarVii commented on app/models/badge_template.rb
> +class BadgeTemplate < ApplicationRecord
не совсем понятно для чего нужна эта модель. Достаточно иметь мождель Badge у которой будет связь с юзером. А тут почему-то ни укого нет такой связи

2023-12-25 08:27 UTC, VidgarVii requested changes

2023-12-25 08:27 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    @badges = Badge.all
уже есть страница, которая показывает все баджи

2023-12-25 08:27 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +
по ТЗ у админа должна быть возможность создавать баджи

2023-12-25 08:27 UTC, VidgarVii commented on app/controllers/test_passings_controller.rb
> +    @test_passing.update!(successful: true) if @test_passing.successful?
в прошлый разу же писал, что не стоит работу с моделью размазывать по коду. Эта работа происходит в самой моделе. Есть метод accept!, вот там можно устанавливить successful

2023-12-25 08:27 UTC, VidgarVii commented on app/services/badge_award_processing.rb
> +    Badge.all.each do |badge|
лучше используй find_each для итераций.
метод .all почти не используют. Так как если в БД окажется большое кол-во данных, то данный метод полностью заполнит оперативную память.  И сервер зависнет

2023-12-25 08:27 UTC, VidgarVii commented on app/services/badge_level_checker.rb
> +class BadgeLevelChecker
все сервисы, которые отвечают за проверку, можно сгруппировать в модуль. Чтобы не было бардака в папке сервисы и код воспринимался лучше

2023-12-25 08:27 UTC, VidgarVii commented on app/services/badge_level_checker.rb
> +    BadgeAwarder.new(@user, @badge).call
судя по названию класса BadgeLevelChecker, он должен только делать проверку. Выдача баджа этол грубый сайд эффект. Код становится очень запутанным и сложным

2023-12-25 08:27 UTC, VidgarVii commented on app/services/get_user_successful_passed_tests_by_ids.rb
> +class GetUserSuccessfulPassedTestsByIds
Используй наследование классов. Логику надо абстрагировать в 1 месте, а не распылять по отдельным разным! классам. Повтори уроки по ООП

2023-12-25 08:27 UTC, VidgarVii commented on app/services/badge_awarder.rb
> +class BadgeAwarder
сомнительное решение использовать класс ради 1 строчки кода

2023-12-25 08:27 UTC, VidgarVii commented on app/services/badge_type_resolver.rb
> +class BadgeTypeResolver
аналогично как и BadgeAwarder. Тут просто прячешь методы за классами. Тут нет порядка, нет абстрагирования логики по функционалу. Вызов правил можно было оставить в BadgeAwardProcessing
Метод call написан без учёта масштабирования. Что будет если баджей станет сотни? 
Посмотри внимательно ролик, который я скинул. По коду видно, что он не был просмотрен внимательно

2023-12-26 05:10 UTC, VidgarVii requested changes

2023-12-26 05:10 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +    binding.pry
отладочный код надо убирать

2023-12-26 05:10 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    @badges = Badge.all
не исправлено

2023-12-26 05:10 UTC, VidgarVii commented on app/controllers/test_passings_controller.rb
> +    @test_passing.update!(successful: true) if @test_passing.successful?
не исправлено

2023-12-26 05:10 UTC, VidgarVii commented on db/migrate/20231212204958_create_badge_templates.rb
> +    create_table :badge_templates do |t|
нет такой модели. миграцию нужно удалить

2023-12-26 05:10 UTC, VidgarVii commented on db/migrate/20231224110402_add_name_to_badge.rb
> +end
так миграции делать мы не учили. Создавать таблицу в 1 ПР надо с помощью 1 миграции, а не 10

2023-12-27 08:53 UTC, merged