Задание 18 (Таймер)
kshnyakin/test-guru pull request #18
Opened 2023-12-24 16:01 UTC by kshnyakin

# Таймер
Разработайте функционал который позволит администраторам создавать тесты с таймером,
а пользователям - проходить такие тесты за отведённое время. При истечении времени таймера тест считается не пройденным.

* Администратор должен иметь возможность задавать таймер прохождения теста, например, 15 минут
* При истечении таймера во время прохождения теста пользователь автоматически перенаправляется на страницу с результатом теста
* При прохождении теста пользователь должен видеть оставшееся количество времени
* Пользователь не должен иметь возможность как-либо подделать установленное время прохождения теста

2023-12-26 05:00 UTC, VidgarVii requested changes

2023-12-26 05:00 UTC, VidgarVii commented on app/controllers/test_passings_controller.rb
> +  def test_time_expired?
этой логике не место в контроллере. Тем более уже есть метод, который отвечает завершен ли тест. Стоит работать с ним

2023-12-26 05:00 UTC, VidgarVii commented on app/javascript/utilities/test-timer.js
> +
тут надо еще сабмитеть форму

2023-12-26 22:25 UTC, kshnyakin commented on app/controllers/test_passings_controller.rb
> +  def test_time_expired?
отрефакторил

2023-12-26 22:25 UTC, kshnyakin commented on app/javascript/utilities/test-timer.js
> +
зарезолвил, ошибка у меня еще была, что в js - миллисекунды, дополнительно не множил на 1000 при переводи из секунд)))

2023-12-27 08:58 UTC, VidgarVii commented on app/javascript/utilities/test-timer.js
> +        var seconds = Math.floor(difference / 1000);
Var давно уже устарел. Безопасней использовать let и const

2023-12-27 09:06 UTC, kshnyakin commented on app/javascript/utilities/test-timer.js
> +        var seconds = Math.floor(difference / 1000);
пофиксил

2023-12-27 09:11 UTC, merged