Задание по основам Rails-моделей
kshnyakin/test-guru pull request #2
Opened 2023-07-11 21:47 UTC by kshnyakin

1) Созданы Rails-модели с нужными атрибутами для следующих сущностей:
Тест / Вопрос / Ответ / Пользователь / Категория

2) С помощью механизма миграций, добавлены ограничения целостности на уровне БД в соответствующих таблицах для необходимых атрибутов так, чтобы они не могли содержать значение NULL

3) С помощью механизма миграций добавьте значения по умолчанию: Для уровня Теста / Для атрибута correct у Ответа.

2023-07-12 05:29 UTC, VidgarVii requested changes

2023-07-12 05:29 UTC, VidgarVii commented on db/migrate/20230711211125_add_not_null_category_id_to_tests.rb
> +    change_column_null(:tests, :category_id, false)
не стоит добавлять отдельные миграции для изменения полей в одном ПР. Миграции всегда являются опасным местом в ПО. Так как меняют схему базы. И всегда стараются минимизировать кол-во миграций.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу. Все остальные миграции являются обычным оверхедом

Пример
```
t.string :title, null: false 
```
Большое кол-во миграций увеличивает время развёртывания ПО. Так же миграция является местом риска, так как может сломать существующую базу. Еще они имеют свойство протухать и быть не актуальными или не рабочими. По этому всегда стараются минимизировать кол-во миграций.

2023-07-12 05:29 UTC, VidgarVii commented on db/schema.rb
> +
во всех полях не хватает ограничение null: false, не думаю что пустые данные нам как-то полезны

2023-07-12 05:29 UTC, VidgarVii commented on db/migrate/20230711210812_create_answers.rb
> +      t.integer :question_id
вспоминаем урок sql. Для отношений нужны не просто поля, а так же еще внешние ключи

2023-07-12 06:43 UTC, kshnyakin commented on db/migrate/20230711210812_create_answers.rb
> +      t.integer :question_id
Да, без этого никак, в предыдущем курсе по Ruby научили парадигме: если нет в ТЗ - значит не делать, не сделал их в связи с тем, что в ТЗ не было ни строчки про реляционную связанность.

2023-07-12 06:43 UTC, kshnyakin commented on db/schema.rb
> +
ок, добавлю

2023-07-12 07:00 UTC, kshnyakin commented on db/migrate/20230711211125_add_not_null_category_id_to_tests.rb
> +    change_column_null(:tests, :category_id, false)
Ок, я думал, что в задании как раз проверяется как усвоен процесс изменения с помощью миграции уже созданных таблиц в БД, все перенесу в одну.

2023-07-12 07:21 UTC, VidgarVii requested changes

2023-07-12 07:21 UTC, VidgarVii commented on db/migrate/20230711210433_create_tests.rb
> +      t.references :category
1. нет внешних ключей.
2. не прописан null: false. Нам не нужны тесты без категорий и автора.
Кстати для теста нам еще понадобиться автор. Это юзер который создал тест. Но при этом по названию колонки должно быть понятно, что речь идёт именно об авторе теста. Предлагаю это сделать в текущем ПР.

2023-07-12 08:29 UTC, kshnyakin commented on db/migrate/20230711210433_create_tests.rb
> +      t.references :category
добавил внешний ключ на User  с названием author_id

2023-07-12 14:11 UTC, VidgarVii requested changes

2023-07-12 14:11 UTC, VidgarVii commented on db/migrate/20230711210433_create_tests.rb
> +      t.references :author, index: true, null: false, foreign_key: {to_table: :users}
index создаётся по дефолту

2023-07-12 14:11 UTC, VidgarVii commented on db/migrate/20230711210648_create_questions.rb
> +      t.references :test
тут не исправлено

2023-07-12 14:11 UTC, VidgarVii commented on db/migrate/20230711210812_create_answers.rb
> +      t.references :question
тут не исправлено

2023-07-12 14:11 UTC, VidgarVii commented on db/migrate/20230711210433_create_tests.rb
> +      t.references :category, null: false
всем связям нужен внешний ключ

2023-07-12 20:00 UTC, kshnyakin commented on db/migrate/20230711210433_create_tests.rb
> +      t.references :author, index: true, null: false, foreign_key: {to_table: :users}
убрал

2023-07-12 20:00 UTC, kshnyakin commented on db/migrate/20230711210648_create_questions.rb
> +      t.references :test
поправил

2023-07-12 20:00 UTC, kshnyakin commented on db/migrate/20230711210812_create_answers.rb
> +      t.references :question
поправил

2023-07-12 20:00 UTC, kshnyakin commented on db/migrate/20230711210433_create_tests.rb
> +      t.references :category, null: false
поправил, почему-то засело на подкорке, что **reference** будет достаточно, освежил знания)

2023-07-13 05:20 UTC, VidgarVii requested changes

2023-07-13 05:20 UTC, VidgarVii commented on db/migrate/20230711210648_create_questions.rb
> +      t.references :test, foreign_key: true
null: false

2023-07-13 05:20 UTC, VidgarVii commented on db/migrate/20230711210812_create_answers.rb
> +      t.references :question, foreign_key: true
null: false

2023-07-13 06:27 UTC, kshnyakin commented on db/migrate/20230711210648_create_questions.rb
> +      t.references :test, foreign_key: true
Почему о том, что здесь reference - не optional не сказали, когда жестко фиксировали наличие автора и привязки к категории у Теста?

Обязательность внешнего ключа не всегда true, например тут думалось, что вопросы могут быть в некоем пуле, который не используется в тестах, а на модерации.

2023-07-13 18:51 UTC, merged