Задание к уроку "Интерфейс запросов ActiveRecord"
kshnyakin/test-guru pull request #3
Opened 2023-07-13 21:40 UTC by kshnyakin

1) Создал набор начальных данных для всех существующих моделей в файле db/seeds.rb

2) Создал инстанс-метод в модели User, который принимает в качестве аргумента значение уровня сложности и 
возвращает список всех Тестов, которые проходит или когда-либо проходил Пользователь на этом уровне сложности.

3) Создал метод класса в модели Test, который возвращает отсортированный по убыванию массив названий всех Тестов у которых Категория называется определённым образом (название категории передается в метод в качестве аргумента).

2023-07-14 13:52 UTC, VidgarVii requested changes

2023-07-14 13:52 UTC, VidgarVii commented on app/models/test.rb
> +    self.where(category_id: category.id).order(:title)
здесь будет два отдельных запроса к базе, это не очень оптимально
несложно записать все в один запрос использую JOIN. Запомни простое правило. Если надо что-то получить из БД. То 100% делегируй задачу базе. Пусть данными агрегирует база. Для этого и был создан SQL. А ОРМ тебе поможет написать запрос проще и безопасней

2023-07-14 13:52 UTC, VidgarVii commented on db/seeds.rb
> +  Category.create(title: attr)
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2023-07-14 13:52 UTC, VidgarVii commented on db/seeds.rb
> +hr_category = Category.find_by(title: 'HR')
все эти лишние запросы можно избежать, если пользоваться данными которые возвращает метод create.
Посмотри внимательно на код в комментарии в этом файле. Чем он плох?
Не стоит писать свои не оптимальные велосипеды, когда есть готовый...

2023-07-14 13:52 UTC, VidgarVii commented on db/seeds.rb
> +puts
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2023-07-14 13:52 UTC, VidgarVii commented on db/seeds.rb
> +puts
очень странный пустой путс

2023-07-15 13:40 UTC, kshnyakin commented on db/seeds.rb
> +puts
Добавлю рубокоп в проект, надоело на этом ловиться)))

2023-07-15 20:05 UTC, kshnyakin commented on db/seeds.rb
> +  Category.create(title: attr)
Пофиксил.

2023-07-15 20:06 UTC, kshnyakin commented on db/seeds.rb
> +puts
Отладочные штуки, убрал

2023-07-15 21:35 UTC, kshnyakin commented on db/seeds.rb
> +hr_category = Category.find_by(title: 'HR')
Отрефакторил.

2023-07-15 21:35 UTC, kshnyakin commented on app/models/test.rb
> +    self.where(category_id: category.id).order(:title)
переписал метод на joins...

2023-07-16 09:02 UTC, VidgarVii requested changes

2023-07-16 09:02 UTC, VidgarVii commented on .rubocop.yml
> +  Enabled: false
https://github.com/kshnyakin/test-guru/pull/3#discussion_r1263763546

2023-07-16 09:02 UTC, VidgarVii commented on .rubocop.yml
> +  Enabled: false
FrozenStringLiteral уменьшает потребление памяти. Отключать её точно не стоит

2023-07-16 09:02 UTC, VidgarVii commented on Gemfile
> +  gem 'pry'
https://github.com/pry/pry-rails
https://dev.to/zeeshan1414/how-to-debug-your-rails-app-using-pry-rails-36cf

2023-07-16 09:02 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins('INNER JOIN categories ON tests.category_id = categories.id')
можно (и рекомендуется)  писать так:
```ruby
joins(...)...
```
т.е. без явного указания объекта у которого вызывается метод
потому что в данном случае объектом является класс `Test` и ему равен `self` внутри класс-метода
по дефолту, при вызове метода без указания объекта он вызывается у `self`, т.е. в текущем варианте как раз у `Test`

2023-07-16 09:02 UTC, VidgarVii commented on app/models/test.rb
> +        .where(categories: { title: category_title }).order(:title)
ТЗ: "Создайте метод класса в модели Test, который возвращает отсортированный по убыванию **массив названий всех Тестов** у

2023-07-16 09:02 UTC, VidgarVii commented on app/models/test.rb
> +  end
для удобства чтения и редактирования можно переносить зачейненные вызовы вот так:
```ruby
  joins(...)
    .where(...)
    .order(...)
    ...
```

2023-07-16 09:51 UTC, kshnyakin commented on app/models/test.rb
> +  end
Исправил

2023-07-16 09:52 UTC, kshnyakin commented on app/models/test.rb
> +        .where(categories: { title: category_title }).order(:title)
добавил :desc.

2023-07-16 09:55 UTC, kshnyakin commented on app/models/test.rb
> +    Test.joins('INNER JOIN categories ON tests.category_id = categories.id')
скорректировался

2023-07-16 09:57 UTC, kshnyakin commented on .rubocop.yml
> +  Enabled: false
добавил, friendly fire - rubocop свой конф файл не уберег)

2023-07-16 09:57 UTC, kshnyakin commented on .rubocop.yml
> +  Enabled: false
Включил и отдельным коммитом везде проставил, где просился

2023-07-16 09:57 UTC, kshnyakin commented on app/models/test.rb
> +    Test.joins('INNER JOIN categories ON tests.category_id = categories.id')
скорректировал

2023-07-16 09:58 UTC, kshnyakin commented on app/models/test.rb
> +  end
скорректировал

2023-07-16 10:01 UTC, kshnyakin commented on Gemfile
> +  gem 'pry'
добавил pry-rails в проект.

2023-07-17 04:47 UTC, VidgarVii requested changes

2023-07-17 04:47 UTC, VidgarVii commented on app/models/test.rb
> +      .order(title: :desc)
Не исправлено
https://github.com/kshnyakin/test-guru/pull/3#discussion_r1264643880
Читаем еще раз внимательно ТЗ. Что должен возвращать метод?

2023-07-17 06:08 UTC, kshnyakin commented on app/models/test.rb
> +      .order(title: :desc)
```
    joins('INNER JOIN categories ON tests.category_id = categories.id')
      .where(categories: { title: category_title })
      .order(title: :desc)
      .pluck(:title)
```

2023-07-17 21:30 UTC, merged