Ассоциации моделей
kshnyakin/test-guru pull request #4
Opened 2023-07-17 21:41 UTC by kshnyakin

1. Создайте ER-диаграмму проекта TestGuru, основываясь на сущностях моделей которые были определены в предыдущем задании. Разместите её на странице GitHub вашего репозитория в разделе GitHub wiki. В качестве инструмента рекомендуется использовать [draw.io](https://draw.io/)

2. Определил ассоциации в моделях:
* Между Тестами и Категориями
* Между Тестами и Вопросами
* Между Вопросами и Ответами
* Между Тестами и проходящими их Пользователями (учесть, что один и тот же тест могут проходить несколько пользователей одновременно)
* Между Тестом и автором (Пользователем), который его создал.

2023-07-19 04:24 UTC, VidgarVii requested changes

2023-07-19 04:24 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2023-07-19 04:24 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2023-07-19 04:24 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
Еще одно нарушение style guide
Надо соблюдай очередность.
Принято сначала писать belongs_to далее ниже has_
Так мы будем понимать какой код где находится
Пример оформления модели
https://github.com/rubocop-hq/rails-style-guide#macro-style-methods

2023-07-19 04:24 UTC, VidgarVii commented on app/models/test.rb
>      joins('INNER JOIN categories ON tests.category_id = categories.id')
с использованием ассоциации аргумент в методе `joins` можно сильно сократить
в задании "Ассоциации моделей" самое время это сделать

2023-07-19 04:24 UTC, VidgarVii commented on app/models/user.rb
>      Test.joins('INNER JOIN test_passings ON tests.id = test_passings.test_id')
здесь в методе можно значительно упростить код
у тебя теперь есть ассоциация, которая вернет список всех тестов пользователя

2023-07-19 04:24 UTC, VidgarVii commented on app/models/user.rb
>      Test.joins('INNER JOIN test_passings ON tests.id = test_passings.test_id')
так же в сидах теперь, благодаря ассоциациям, можно (и рекомендуется в ООП) передавать объекты для связывания по ключам, вместо аттрибутов: `category: categories[0]`, `author: users[0]` и т.п. (без `_id` , `.id`)

2023-07-19 20:29 UTC, kshnyakin commented on app/models/category.rb
> +  has_many :tests
Добавил необходимые опции.

2023-07-19 20:37 UTC, kshnyakin commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
Пофиксил + добавил в проект rubocop-rails

2023-07-19 20:39 UTC, kshnyakin commented on app/models/user.rb
>      Test.joins('INNER JOIN test_passings ON tests.id = test_passings.test_id')
скорректировал метод с условием появления новых ассоциаций.

Скорректировал seeds.

2023-07-19 21:35 UTC, kshnyakin commented on app/models/test.rb
>      joins('INNER JOIN categories ON tests.category_id = categories.id')
Скорректировался

2023-07-19 21:35 UTC, kshnyakin commented on app/models/question.rb
> +  has_many :answers
Переоформил, спасибо!

2023-07-20 05:30 UTC, VidgarVii commented on db/seeds.rb
> +  backend_category.tests.create!([
про сиды я писал не много другое
https://github.com/kshnyakin/test-guru/pull/4#discussion_r1267520436
`author_id: ivanov_user.id` можно заменить на просто `author: ivanov_user`

2023-07-20 21:32 UTC, kshnyakin commented on db/seeds.rb
> +  backend_category.tests.create!([
Спасибо, поправил + поправил там, где было `test_id`

2023-07-20 21:35 UTC, merged