Часть 6: Rails Model в действии. Часть 3: валидации данных и scope-методы
kshnyakin/test-guru pull request #5
Opened 2023-07-20 21:40 UTC by kshnyakin

2023-07-22 11:41 UTC, VidgarVii requested changes

2023-07-22 11:41 UTC, VidgarVii commented on app/models/answer.rb
> +  validate :validate_answers_quantity, on: %i[create update]
в таком виде вызов валидации не позволит обновить ответ (`answer.update(...)`), если у вопроса их уже создано 4 штуки

2023-07-22 11:41 UTC, VidgarVii commented on app/models/category.rb
> +  default_scope { order(title: :asc) }
`default_scope` глобально меняет поведение всех запросов к модели
поэтому его [рекомендуют](https://github.com/rubocop-hq/rails-style-guide#macro-style-methods) записывать в самом верху класса

2023-07-22 11:41 UTC, VidgarVii commented on app/models/test.rb
> +  # а scope должен возвращать ActiveRcord::Relation
верно. но такой коммент в коде точно не нужен

2023-07-22 11:41 UTC, VidgarVii commented on app/models/answer.rb
> +  def validate_answers_quantity
данный метод не является публичным методом экземпляра класса.
Он должен быть приватным

2023-07-22 11:41 UTC, VidgarVii commented on app/models/test.rb
> +  def validate_title_level_uniqueness
для уникальности полей есть готовое решение. Почитай внимательно документацию 
http://rusrails.ru/active-record-validations#uniqueness

2023-07-22 12:55 UTC, kshnyakin commented on app/models/category.rb
> +  default_scope { order(title: :asc) }
Пофиксил, запомнил

2023-07-22 12:56 UTC, kshnyakin commented on app/models/answer.rb
> +  def validate_answers_quantity
Убрал, наверное его можно было в комментариях к коды указать.

2023-07-22 12:56 UTC, kshnyakin commented on app/models/test.rb
> +  # а scope должен возвращать ActiveRcord::Relation
Убрал, наверное его можно было в комментариях к коды указать.

2023-07-22 12:57 UTC, kshnyakin commented on app/models/answer.rb
> +  def validate_answers_quantity
перенес в private

2023-07-22 13:01 UTC, kshnyakin commented on app/models/test.rb
> +  def validate_title_level_uniqueness
Да, не видел такой возможности, не прочитал, спасибо

2023-07-22 21:25 UTC, kshnyakin commented on app/models/answer.rb
> +  validate :validate_answers_quantity, on: %i[create update]
Подумал над логикой, переписал

2023-07-22 21:27 UTC, kshnyakin commented on app/models/answer.rb
> +    return unless new_record? || (question.answers.pluck(:id).exclude? id)
проверку делаем только если это новая запись, или в результате обновления хотят изменить привязку ответа к id другого вопроса (проверяется сколько у этого вопроса уже есть ответов)

2023-07-23 05:55 UTC, VidgarVii requested changes

2023-07-23 05:55 UTC, VidgarVii commented on app/models/answer.rb
> +    return unless new_record? || (question.answers.pluck(:id).exclude? id)
сомнительный костыль. валидация нужна при создании нового объекта. Посмотри внимательно на 7 строчку

2023-07-23 06:41 UTC, kshnyakin commented on app/models/answer.rb
> +    return unless new_record? || (question.answers.pluck(:id).exclude? id)
убрал костыль, оставил валидацию только на создание. будем полагать, что при обновлении **answer** - нельзя будет менять его **question_id**

2023-07-23 06:41 UTC, kshnyakin commented on app/models/answer.rb
> +    return unless new_record? || (question.answers.pluck(:id).exclude? id)
не актуально

2023-07-24 05:44 UTC, VidgarVii commented on app/models/test.rb
> +                    on: %i[create update]
тут on: %i[create update] лишний

2023-07-24 06:21 UTC, kshnyakin commented on app/models/test.rb
> +                    on: %i[create update]
Убрал.

2023-07-24 06:24 UTC, merged