Rails контроллер в действии.
kshnyakin/test-guru pull request #6
Opened 2023-07-26 22:00 UTC by kshnyakin

1. Создайте ресурс Вопросов, вложенный в ресурс Тестов

2. Следуя принципам  REST, cоздайте контроллер для ресурса вопросов и реализуйте методы:
* Просмотра списка вопросов теста
* Просмотра конкретного вопроса теста
* Создания вопроса. Используйте шаблон с HTML формой. Идентификатор теста к которому принадлежит вопрос можно указать явно в составе URL значения атрибута action в тэге form
* Удаления вопроса
* Используйте метод render внутри действия контроллера чтобы вернуть ответ клиенту как простой текст (plain text) или HTML
* Используйте обратный вызов при поиске теста в контроллере ресурса вопросов

3. Напишите обработку исключения для случая когда вопрос не был найден

2023-07-27 12:52 UTC, VidgarVii requested changes

2023-07-27 12:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    respond_to do |format|
про различные форматы в тз ни чего не сказано. Мы будем работать в этом проекте только с 1 форматом

2023-07-27 12:52 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions, only: %i[index show new create destroy]
можно убрать only
экшен update добавим уже в следующем тз

2023-07-27 12:52 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions, only: %i[index show new create destroy]
для "облегчения" роутинга рекомендуется использовать (где это возможно и приемлемо) опцию `shallow: true`
Это уменьшит кол-во запросов в контроллере. Упростит код и укоротит http запрос
[вот](http://rusrails.ru/rails-routing#melkoe-vlozhenie)

2023-07-27 12:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    raise ActiveRecord::RecordNotFound unless question
абсолютно не нужная операция в этом методе.
Чтобы найти вопрос достаточно знать его id
И воспользоваться методом find, который в случаи отсутствия вопроса выкинет ActiveRecord::RecordNotFound

2023-07-27 12:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    if question
если вопроса нет, то контроллер должен вернуть 404 статус

2023-07-27 12:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      render plain: 'id вопроса для удаления не принадлежит данному тесту'
не совсем по рест.
использую shallow в роутах. Эта проверка не понадобится

2023-07-27 12:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    render plain: "Вопрос (#{question.title}) был успешно создан"
При создании и обновлении ресурса нужно проверять валидацию, которая была прописана в модели. И если валидация не прошла, то рендерят форму и выводит ошибки(ошибки будем показывать далее по уроку)
По этому тут надо добавить проверку, записался ли объект в базу?
стандартный подход экшена create такой
```
@question = @test.questions.build(question_params)
if @question.save
  redirect_to @question
else
  render :new
end
```

2023-07-27 14:48 UTC, kshnyakin commented on app/controllers/questions_controller.rb
> +    respond_to do |format|
Убрал + убрал зарегистрированный в иницизизаторе MIME type

2023-07-28 04:12 UTC, kshnyakin commented on config/routes.rb
> +    resources :questions, only: %i[index show new create destroy]
Переписал

2023-07-28 06:49 UTC, kshnyakin commented on app/controllers/questions_controller.rb
> +    render plain: "Вопрос (#{question.title}) был успешно создан"
привел в соответствие

2023-07-28 06:49 UTC, kshnyakin commented on app/controllers/questions_controller.rb
> +      render plain: 'id вопроса для удаления не принадлежит данному тесту'
проработал

2023-07-28 06:49 UTC, kshnyakin commented on app/controllers/questions_controller.rb
> +    if question
добавил

2023-07-28 06:50 UTC, kshnyakin commented on app/controllers/questions_controller.rb
> +    raise ActiveRecord::RecordNotFound unless question
переделал метод

2023-07-28 10:03 UTC, vkurennov requested changes

2023-07-28 10:03 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  before_action :test, only: %i[create new index]
лучше называть методы вроде load_test или set_test. либо есть вариант оставить как у тебя, но тогда не нужны before_action, т.к. надо внутри экшенов обращаться к самим методам test/question, а не к инстанс-переменным, тогда загрузка будет происходить при первом приближении. а тут получается 2 подхода смешены. выбери один и его используй (рекомендую с before_action и инстанс-переменными, это стандарт де-факто)

2023-07-28 10:03 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id].to_i)
не нужно приводить к целому значение, рельсы умеют работать и со строкой, приводя к нужным значениям под капотом. рельсы вообще многое делают за разработчика, стоит им в этом довериться)

2023-07-28 10:03 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      render file: Rails.root.join('public/500'), status: :internal_server_error
тут некорректно, если destroy вернул false (что может быть только если внутри коллбеков модели была отмена удаления, т.е. это вручную заданное поведение), то да, объект не удален, но это не ошибка сервера, это так логика написана. Если же там ошибка случится, то и так 500я ошибка будет, т.к. будет выброшено исключение. в общем, тут в принципе не нужна такая обработка, исходим из того, что объект будет удален успешно и раз нет логики отмены удаления, то и обрабатывать ее не нужно

2023-07-28 10:03 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @test ||= Test.find(params[:test_id].to_i)
to_i здесь и далее лишние

2023-07-28 10:03 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    raise ActiveRecord::RecordNotFound unless @question
find и так выбрасывает это исключение, если не найдет объект, так что это лишнее действие. т.е. find либо вернет объект, либо выбросит исключение, поэтому `unless @question` в принципе никогда не выполнится, find не возвращает nil или false

2023-07-28 11:40 UTC, kshnyakin commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id].to_i)
Доверился, убрал где было преобразование `params[:id].to_i`

2023-07-28 11:43 UTC, kshnyakin commented on app/controllers/questions_controller.rb
> +    raise ActiveRecord::RecordNotFound unless @question
поправил

2023-07-28 11:52 UTC, kshnyakin commented on app/controllers/questions_controller.rb
> +    @test ||= Test.find(params[:test_id].to_i)
ликвидировал

2023-07-28 11:56 UTC, kshnyakin commented on app/controllers/questions_controller.rb
> +      render file: Rails.root.join('public/500'), status: :internal_server_error
Убрал обработку. Полагаемся на успешное удаление.

2023-07-28 12:05 UTC, kshnyakin commented on app/controllers/questions_controller.rb
> +  before_action :test, only: %i[create new index]
Это ко мне Rubocop пристал - мол переименуй, да переименуй. Скорректировал, rubocop ругается: хочет, чтобы инстанс-переменная была равна названию методы, который ее достает:

```
app/controllers/questions_controller.rb:37:5: C: [Correctable] Naming/MemoizedInstanceVariableName: Memoized variable @test does not match method name load_test. Use @load_test instead.
    @test ||= Test.find(params[:test_id])
```

2023-07-28 12:14 UTC, kshnyakin commented on app/controllers/questions_controller.rb
> +      render file: Rails.root.join('public/500'), status: :internal_server_error
Добавил только редирект на список вопросов того же теста, вопрос которого мы удалили, чтобы у пользователя не создавалось впечатления, что ничего не произошло. (по сути просто перезагрузка страницы)

2023-07-28 14:28 UTC, vkurennov approved these changes

2023-07-30 20:42 UTC, merged