Часть 8: Представление ресурсов. Rail Views в действии
kshnyakin/test-guru pull request #7
Opened 2023-07-30 20:46 UTC by kshnyakin

1. Реализуйте все стандартные действия вместе с представлениями (видами) для ресурса вопросов:
Список вопросов теста должен выводиться на той же странице, что и сам тест
Используйте фрагменты представлений там, где это уместно
Для того чтобы метод form_with смог сформировать верный URL используйте вызов form_with model: [@parent, @child]
В представлениях должны быть ссылки для навигации между страницами приложения

2. Добавьте футер в котором будет выводиться текущий год, имя автора, название проекта (в виде ссылки на GitHub-репозиторий проекта), его краткое описание и ссылка с текстом "Учебный проект в онлайн-школе Thinknetica", ведущая на адрес [thinknetica.com](http://thinknetica.com/)

3. Напишите хэлперы:
Для заголовка формы создания и редактирования вопроса. Это должен быть один метод question_header который в форме создания вопроса будет выводить Create New <Test Title> Question, а в форме редактирования Edit <Test Title> Question
Для вывода текущего года в футере
Для формирования ссылки на GitHub репозиторий: github_url(author, repo)

4. Добавьте в представление списка тестов количество вопросов для каждого теста

2023-08-04 05:22 UTC, VidgarVii requested changes

2023-08-04 05:22 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +  end
этот хелпер формирует строку, а не ссылку (html)

2023-08-04 05:22 UTC, VidgarVii commented on app/views/questions/_question.html.erb
> +</tr>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2023-08-04 05:22 UTC, VidgarVii commented on app/views/questions/index.html.erb
>  <% if @questions.size < 1 %>
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2023-08-04 05:22 UTC, VidgarVii commented on app/views/shared/_questions_list.html.erb
> +    <% questions.each do |question| %>
для рендера коллекций обычно используют render collection
http://rusrails.ru/layouts-and-rendering-in-rails#rendering-kollektsiy

```ruby
  render @questions
```

- Это разгрузит данный файл
- Наведет порядок. Вся работа с нужными ресурсами будет вестись в своей папке
- Позволит удобней кешировать куски страницы

в скринкасте про лэйауты и паршелы рассказывается про рекомендуемый вариант рендеринга коллекций (примерно после 20:30)

2023-08-04 05:22 UTC, VidgarVii commented on app/views/shared/_questions_list.html.erb
> +<% if questions.size > 0 %>
эту проверку можно сделать на много проще
https://stackoverflow.com/questions/1027871/rails-an-elegant-way-to-display-a-message-when-there-are-no-elements-in-databas

2023-08-04 06:30 UTC, kshnyakin commented on app/helpers/application_helper.rb
> +  end
Скорректировал на вормирование html <a>

2023-08-04 16:35 UTC, kshnyakin commented on app/views/questions/_question.html.erb
> +</tr>
поправил

2023-08-04 20:39 UTC, kshnyakin commented on app/views/shared/_questions_list.html.erb
> +    <% questions.each do |question| %>
Да, пофиксил, ранее использовал но тут не очень понятно было из какой подпапки **views** будет взят нужный **partial**.

2023-08-04 20:42 UTC, kshnyakin commented on app/views/shared/_questions_list.html.erb
> +<% if questions.size > 0 %>
сделал проверку вида: 

```
<% if questions.each do |question| %>
  ...
<% end.empty? %>
  You have no questions.
<% end %>
```

2023-08-04 21:08 UTC, kshnyakin commented on app/views/questions/index.html.erb
>  <% if @questions.size < 1 %>
* экшен index в классе QuestionsController лишний - удалил

2023-08-04 23:55 UTC, kshnyakin commented on app/views/questions/index.html.erb
>  <% if @questions.size < 1 %>
Скорректировался

2023-08-06 07:01 UTC, VidgarVii requested changes

2023-08-06 07:01 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @test = Test.find(params[:id])
это уже делается в колбеке

2023-08-06 07:01 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  end
при создании теста все параметры также должны приходить в объекте test

2023-08-06 07:01 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +  def question_header(action, test_title)
тут достаточно пепедать сам объект вопроса и проверять его состояние .persisted?` или `.new_record?

2023-08-06 07:01 UTC, VidgarVii commented on app/views/questions/index.html.erb
>  <% if @questions.size < 1 %>
https://github.com/kshnyakin/test-guru/pull/7/files#r1283991415
не исправлено.
Там написано, что этот файл больше не нужен

2023-08-06 07:01 UTC, VidgarVii commented on app/views/questions/show.html.erb
> +<%= link_to "Вернуться к вопросам теста", test_path(@question.test_id) %>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2023-08-06 07:10 UTC, kshnyakin commented on app/controllers/tests_controller.rb
> +    @test = Test.find(params[:id])
добавил выполнение коллбэка на поиск тест и для экшена `update`

2023-08-06 07:18 UTC, kshnyakin commented on app/helpers/questions_helper.rb
> +  def question_header(action, test_title)
Отрефакторил

2023-08-06 07:20 UTC, kshnyakin commented on app/views/questions/index.html.erb
>  <% if @questions.size < 1 %>
Удалил представление index для модели **Question**.

2023-08-06 07:23 UTC, kshnyakin commented on app/views/questions/show.html.erb
> +<%= link_to "Вернуться к вопросам теста", test_path(@question.test_id) %>
Добавил

2023-08-06 07:26 UTC, kshnyakin commented on app/controllers/tests_controller.rb
> +  end
При одном и том же партиале формы - на создание приходили параметры вне объекта test, а при обновлении - в объекте test, сейчас почему то работает нормально - и создание и обновление: параметры присылаются в объекте `test`

2023-08-06 07:34 UTC, kshnyakin commented on app/controllers/tests_controller.rb
> +  end
Поправил эту ошибку еще и при создании / обновлении вопросов. Ошибка была из-за того, что в методе NEW не был инициализирован экземпляр создаваемой модели

```
def new
  @test = Test.new
end
```

2023-08-07 07:09 UTC, merged