Создание логики приложения
kshnyakin/test-guru pull request #8
Opened 2023-08-07 07:18 UTC by kshnyakin

1. Сделайте назначение следующего вопроса в модели TestPassage с помощью обратного вызова
2. Доработайте шаблон результата прохождения теста:
Выводите сообщение и процент успеха в зависимости от количества правильных ответов
Если процент успеха >= 85% число должно быть зелёного цвета и сообщение должно говорить об успешном прохождении теста
Если процент успеха < 85% число должно быть красного цвета и сообщение должно говорить о том что тест не пройден
Добавьте навигацию в виде ссылки на список всех тестов
3. Доработайте шаблон отображения прохождения теста:
Выводите номер текущего вопроса и общее количество вопросов теста

Возможен более простой способ реализации проверки правильного ответа:

correct_answers.ids.sort == answer_ids.map(&:to_i).sort

2023-08-17 14:03 UTC, VidgarVii requested changes

2023-08-17 14:03 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +    flash[:notice] = 'You have successfully logged out.'
как это относится к странице редактирования ответа?

2023-08-17 14:03 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :correct).to_h
вызов to_h тут совсем лишний

2023-08-17 14:03 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :set_user, only: %i[start]
для 1 экшена колбек не объявляют. Это усложняет код и дебажить будет сложнее

2023-08-17 14:03 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +      passing_status: 'in_progress'
1 по ТЗ должен быть метод, который говорит завершен ли тест.
2 Для статусов объекта используют паттерн конечный автомат. Сейчас пока рано его внедрять. Предлагаю вообще избавиться от параметра passing_status. Если пока не хочется его удалять. Можно установить статус через колбек (при создании объекта)
Учитывая всё это, используя методы ассоциаций можно сократить код до 
`@user..tests.push(@test)`

2023-08-17 14:03 UTC, VidgarVii commented on app/helpers/test_passings_helper.rb
> +end
данный модуль нужен для упрощение верстки сайта, а не хранения бизнес логики и запрос в бд. Всему этому коду (кроме формирования хтмл и контекста) тут не место

2023-08-17 14:03 UTC, VidgarVii commented on app/models/test_passing.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
нужно учесть, что пользователь может не выбрать ни одного ответа из предложенных и код от этого не должен падать

2023-08-17 14:03 UTC, VidgarVii commented on app/models/test_passing.rb
> +      self.current_question = next_question
очень сильно размазан код определения текущего вопроса. Стоит абстрагировать это всё в 1 место. По ТЗ это должен быть колбек

2023-08-17 14:03 UTC, VidgarVii commented on app/helpers/test_passings_helper.rb
> +    percentage >= 85 ? 'green' : 'red'
`percentage >= 85`
вот эта операция сравнения - это по сути бизнес-логика о которой вьюхе знать не надо и ее правильно будет поместить в модель, а здесь оставить что-то типа:

```html
  <% if @test_passage.successful? %>
```

2023-08-17 14:03 UTC, VidgarVii commented on app/helpers/test_passings_helper.rb
> +    percentage >= 85 ? 'green' : 'red'
лучше "магические цифры" хранить в константах с "говорящими именами"
например `SUCCESS_RATIO`

2023-08-17 14:03 UTC, VidgarVii commented on app/views/test_passings/result.html.erb
> +
No new lina at end of file

2023-08-17 14:03 UTC, VidgarVii commented on config/routes.rb
> +    end
когда всего одна строчка, можно написать
```ruby
post :start, on: :member
```

2023-08-17 15:11 UTC, kshnyakin commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :correct).to_h
Убрал.

2023-08-17 15:14 UTC, kshnyakin commented on app/controllers/tests_controller.rb
> +  before_action :set_user, only: %i[start]
Убрал, сделал вызов `set_user` в самом экшене `start`

2023-08-17 15:18 UTC, kshnyakin commented on app/views/test_passings/result.html.erb
> +
Вроде есть пустая строка в конце файла, убрал из нее пробел, он мешал всему?

2023-08-17 15:40 UTC, kshnyakin commented on app/models/test_passing.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
Учел, добавил `include_hidden: true` в форму чек-боксов ответов вопроса (app/views/test_passings/show.html.erb)

2023-08-17 15:41 UTC, kshnyakin commented on config/routes.rb
> +    end
Скорректировал)

2023-08-17 15:41 UTC, kshnyakin commented on app/controllers/answers_controller.rb
> +    flash[:notice] = 'You have successfully logged out.'
Не заметил, не убрал

2023-08-17 21:42 UTC, kshnyakin commented on app/controllers/tests_controller.rb
> +      passing_status: 'in_progress'
* Удалил пока что поле `status` - заработал короткий метод `@user..tests.push(@test)`
* Вернул метод `завершен ли тест`

2023-08-17 21:43 UTC, kshnyakin commented on app/models/test_passing.rb
> +      self.current_question = next_question
отрефакторил этот момент

2023-08-17 22:28 UTC, kshnyakin commented on app/helpers/test_passings_helper.rb
> +end
Перенес всю логику в модель

2023-08-17 22:28 UTC, kshnyakin commented on app/helpers/test_passings_helper.rb
> +    percentage >= 85 ? 'green' : 'red'
Отрефакторил

2023-08-18 06:07 UTC, VidgarVii requested changes

2023-08-18 06:07 UTC, VidgarVii commented on app/models/test_passing.rb
> +  end
вот этот вот метод можно было оставить в хелпере.
Бизнес логика тут только проверка успешности прохождения теста. И уже есть такой метод. Лучше было бы его использовать, а не дублировать код

2023-08-18 06:07 UTC, VidgarVii commented on app/models/test_passing.rb
> +  def accept!(answer_ids)
константы и методы надо отделять пустой строкой

2023-08-18 06:07 UTC, VidgarVii commented on app/models/test_passing.rb
> +  SUCCESS_RATIO = 85.freeze
цифры нет смысла фризить

2023-08-18 06:07 UTC, VidgarVii commented on app/models/test_passing.rb
> +  before_validation :before_validation_set_first_question, on: :create
разделяй код на логические блоки пустой строкой. Слипшийся код сложно читается

2023-08-18 06:07 UTC, VidgarVii commented on app/models/test_passing.rb
> +    questions_arr.index(current_question_id) + 1
от переменной тут пользы нет. Если создаётся длинная цепочка вызовов методов, то просто каждый метод переносят на новую строчку. Вспомни как писали методы для моделей Юзер и Тест

2023-08-18 06:07 UTC, VidgarVii commented on app/models/test_passing.rb
> +    questions_arr.index(current_question_id) + 1
Определение текущего номера вопроса неэффективно - ты грузишь id всех вопросов в память. Можно все сделать с помощью запроса - посмотри на код определения следующего вопроса, тут будет схожая логика.

2023-08-18 06:07 UTC, VidgarVii commented on app/views/test_passings/show.html.erb
> +    :id, :body, include_hidden: false do |box| %>
не много странный костыль.
Стабильней было бы решить эту задачу на стороне бекенда. Вообще успешность выполнения кода не должно зависеть от внешних факторов. Да бекнед работает с входящими данными. Но то что юзер может не выбрать ответ это нормальный кейс. И стоит это учесть именно на стороне бекенда.

2023-08-18 06:07 UTC, VidgarVii commented on config/routes.rb
> +    end
тут не отрефачен блок

2023-08-18 06:07 UTC, VidgarVii commented on app/views/answers/index.html.erb
> +<p id="notice"><%= notice %></p>
у нас разве есть такая страница?

2023-08-18 06:07 UTC, VidgarVii commented on app/models/test_passing.rb
> +  before_validation :before_validation_assign_next_question, on: :update
эти два коллбека делают одно и то же по сути
оба устанавливают следующий вопрос
разница лишь в том, что считать следующим вопросом, т.е разница в поиске этого следующего вопроса

(и обрати внимание - оба вызываются с дополнительным условием, на создании или на апдейте)

имеет смысл объединить их в один простой коллбек:

```ruby
before_validation :set_current_question

...

def set_current_question
  self.current_question = next_question
end
```
а всю различающуюся логику поместить уже в метод `next_question`

(коллбеки бывает удобно использовать, но они часто усложняют код и его отладку, если есть возможность не плодить лишние, то ей надо воспользоваться)


вообще с коллбеками нужно осторожно - они не всегда делают то что ты ожидаешь, тогда когда ты ожидаешь ))
бывают ньюансы о которых не догадываешься, особенно при совместной работе нескольких коллбеков и использовании коллбеков с условиями
поэтому если есть возможность упростить коллбеки, то это нужно делать

2023-08-18 10:00 UTC, kshnyakin commented on app/models/test_passing.rb
> +  def accept!(answer_ids)
пофиксил

2023-08-18 10:03 UTC, kshnyakin commented on app/models/test_passing.rb
> +  before_validation :before_validation_set_first_question, on: :create
добавил строку между belongs'ами и коллбэками

2023-08-18 10:05 UTC, kshnyakin commented on config/routes.rb
> +    end
доделал

2023-08-18 10:05 UTC, kshnyakin commented on app/views/answers/index.html.erb
> +<p id="notice"><%= notice %></p>
нету, удалил

2023-08-18 10:06 UTC, kshnyakin commented on app/models/test_passing.rb
> +  SUCCESS_RATIO = 85.freeze
сделал антифриз

2023-08-18 10:42 UTC, kshnyakin commented on app/models/test_passing.rb
> +    questions_arr.index(current_question_id) + 1
Спасибо за наводку кажется правильно понял, что нужно сделать.

2023-08-18 10:48 UTC, kshnyakin commented on app/models/test_passing.rb
> +  before_validation :before_validation_assign_next_question, on: :update
отрефакторил, работоспособно

2023-08-18 10:57 UTC, kshnyakin commented on app/models/test_passing.rb
> +  end
Понял, согласен, отрефакторил.

2023-08-18 11:49 UTC, kshnyakin commented on app/views/test_passings/show.html.erb
> +    :id, :body, include_hidden: false do |box| %>
Отрефакторил, сделал `include_hidden = true`, обрабатываю пустую строку в массиве на уровне определения правильности теста

2023-08-19 15:40 UTC, VidgarVii requested changes

2023-08-19 15:40 UTC, VidgarVii commented on app/models/test_passing.rb
> +  SUCCESS_RATIO = 85
константы пишут в самом вверху класса

2023-08-19 15:40 UTC, VidgarVii commented on app/models/test_passing.rb
> +  end
не исправлено

2023-08-19 15:40 UTC, VidgarVii commented on app/models/test_passing.rb
> +    answer_ids = [] unless answer_ids
по возможности всегда луччше использовать if а не unless. Лучше воспринимается
Вообще можно просто answer_ids переводить в массив без явных проверок

`correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort`

2023-08-19 15:40 UTC, VidgarVii commented on app/models/test_passing.rb
> +    end
а если оба условия не будут верными?
лучше здесь вместо `current_question.nil?` проверять `new_record?` - это более прямолинейно отражает логику: "если новое прохождение теста, то первый вопрос"

2023-08-19 16:09 UTC, kshnyakin commented on app/models/test_passing.rb
> +  SUCCESS_RATIO = 85
поправил

2023-08-19 16:13 UTC, kshnyakin commented on app/models/test_passing.rb
> +    answer_ids = [] unless answer_ids
Понял, скорректировал

2023-08-19 16:19 UTC, kshnyakin commented on app/models/test_passing.rb
> +    end
Пофиксил

2023-08-19 16:21 UTC, kshnyakin commented on app/models/test_passing.rb
> +  end
Да, перенес все с хелпер, а из модели не удалил, глупая ошибка

2023-08-20 20:42 UTC, merged