10. Аутентификация и пользовательские сессии
kshnyakin/test-guru pull request #9
Opened 2023-08-20 20:47 UTC by kshnyakin

1. Добавьте в сессию идентификатор пользователя после его регистрации
2. Создайте хэлпер для flash сообщений
3. Реализуйте выход пользователя из системы
4. Создайте навигацию с названием проекта и ссылками для регистрации/логина/выхода пользователя. Если пользователь находится в системе - выводить сообщение Welcome, <user name> Guru. Название проекта должно быть ссылкой и вести на главную страницу приложения.
5. Разрешите действия над остальными ресурсами только для пользователя который вошел в систему
6. С помощью механизма куки реализуйте перенаправление пользователя после логина на ту страницу куда он хотел попасть изначально
7. Проверяйте формат и уникальность атрибута email для пользователя
8. Используйте объект текущего пользователя при старте прохождения теста

2023-08-27 12:18 UTC, VidgarVii requested changes

2023-08-27 12:18 UTC, VidgarVii commented on app/assets/stylesheets/flash.scss
> +}
пора уже научиться следить за концом файла

2023-08-27 12:18 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      redirect_to session[:url_return_to] || root_path
тут сразу можно удалить запись url_return_to

2023-08-27 12:18 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +  def logout
не по REST

2023-08-27 12:18 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @user = current_user
в этом нет ни какого смысла. Можно сразу обращаться к методу current_user там где нужен юзер

2023-08-27 12:18 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    return unless flash[:alert]
типов флеш сообщений на много больше чем 1 алерт.

2023-08-27 12:18 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +  def flash_alert(flash)
нет смысла пердавать объект флеш. Он и так доступен во вью

2023-08-27 12:18 UTC, VidgarVii commented on config/routes.rb
> +  post :logout, to: 'sessions#logout'
не по REST за удаление ресурса отвечает метод запроса DELETE

2023-08-27 21:55 UTC, kshnyakin commented on app/assets/stylesheets/flash.scss
> +}
Честно проверял весь PR, видимо упустил ((( исправил

2023-08-27 22:13 UTC, kshnyakin commented on app/controllers/sessions_controller.rb
> +      redirect_to session[:url_return_to] || root_path
Добавил: удалил

2023-08-27 22:14 UTC, kshnyakin commented on app/controllers/tests_controller.rb
> +    @user = current_user
Убрал, спасибо!

2023-08-27 22:17 UTC, kshnyakin commented on config/routes.rb
> +  post :logout, to: 'sessions#logout'
Исправил, спасибо

2023-08-27 22:18 UTC, kshnyakin commented on app/controllers/sessions_controller.rb
> +  def logout
поправил на #destroy

2023-08-27 22:19 UTC, kshnyakin commented on app/helpers/application_helper.rb
> +    return unless flash[:alert]
отрефакторил

2023-08-27 22:19 UTC, kshnyakin commented on app/helpers/application_helper.rb
> +  def flash_alert(flash)
отрефакторил

2023-08-28 05:25 UTC, VidgarVii requested changes

2023-08-28 05:25 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      redirect_to session[:url_return_to] || root_path
тут сразу можно удалить запись url_return_to
`redirect_to session.delete(:url_return_to) || root_path`
кстати по ТЗ url_return_to надо хранить в куках, а не в сессиях

2023-08-28 05:25 UTC, VidgarVii commented on config/locales/ru.yml
> +              invalid: не соответствует формату
No new lina at end of file

2023-08-28 06:50 UTC, kshnyakin commented on config/locales/ru.yml
> +              invalid: не соответствует формату
Можете поделиться директивой для rubocop, чтобы он это контролировал?
Поправил

2023-08-28 07:06 UTC, kshnyakin commented on app/controllers/sessions_controller.rb
> +      redirect_to session[:url_return_to] || root_path
Переделал, т.к. у нас сессии реализованы через куки, не возникло диссонанса в том, что если положить url в сессию - то это будет реализация в итоге через Cookie

2023-08-28 07:10 UTC, merged